# This Dockerfile sets up a container for running connect_db.py.
#
# It uses an official Python runtime as a parent image, copies the source
# code into the container, installs dependencies specified in requirements.txt,
# exposes port 80, and runs connect_db.py upon container launch.

FROM python:3.10.13-slim-bullseye

WORKDIR /app

COPY ./src /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

CMD ["python", "connect_db.py"]